"""1st

Revision ID: 6d73fd069cf7
Revises: 
Create Date: 2016-12-02 00:03:40.929024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d73fd069cf7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('passhash', sa.String(length=120), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('store',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=False),
    sa.Column('typeid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['store.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cinema_environment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('comment_id', sa.Integer(), nullable=True),
    sa.Column('ticket_machine', sa.Boolean(), nullable=False),
    sa.Column('reset_seat', sa.Boolean(), nullable=False),
    sa.Column('hall_light', sa.Integer(), nullable=False),
    sa.Column('room_light', sa.Integer(), nullable=False),
    sa.Column('room_number', sa.String(length=4), nullable=False),
    sa.Column('screen_size', sa.Integer(), nullable=False),
    sa.Column('this_seat', sa.Float(), nullable=False),
    sa.Column('best_seat', sa.Float(), nullable=False),
    sa.Column('seat_comfort', sa.Integer(), nullable=False),
    sa.Column('smells', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['comment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cinema_other',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('comment_id', sa.Integer(), nullable=True),
    sa.Column('toilet_clean', sa.Integer(), nullable=True),
    sa.Column('toilet_paper', sa.Boolean(), nullable=True),
    sa.Column('traffic', sa.Integer(), nullable=True),
    sa.Column('restaurant', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['comment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cinema_quality',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('comment_id', sa.Integer(), nullable=True),
    sa.Column('sound_star', sa.Integer(), nullable=False),
    sa.Column('movie_name', sa.String(length=30), nullable=False),
    sa.Column('video_star', sa.Integer(), nullable=False),
    sa.Column('video_comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['comment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cinema_service',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('comment_id', sa.Integer(), nullable=True),
    sa.Column('check_ticket_time', sa.Integer(), nullable=False),
    sa.Column('glass_3d_type', sa.Integer(), nullable=False),
    sa.Column('snack_star', sa.Integer(), nullable=False),
    sa.Column('snack_comment', sa.Text(), nullable=True),
    sa.Column('ads', sa.Integer(), nullable=False),
    sa.Column('staff_star', sa.Integer(), nullable=False),
    sa.Column('staff_comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['comment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('restaurant_environment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('comment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['comment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('restaurant_other',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('comment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['comment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('restaurant_quality',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('comment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['comment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('restaurant_service',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('comment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['comment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('restaurant_service')
    op.drop_table('restaurant_quality')
    op.drop_table('restaurant_other')
    op.drop_table('restaurant_environment')
    op.drop_table('cinema_service')
    op.drop_table('cinema_quality')
    op.drop_table('cinema_other')
    op.drop_table('cinema_environment')
    op.drop_table('comment')
    op.drop_table('user_role')
    op.drop_table('store')
    op.drop_table('user')
    op.drop_table('role')
    # ### end Alembic commands ###
