"""add created_time and updated_time

Revision ID: 808958024cdf
Revises: 6d73fd069cf7
Create Date: 2016-12-04 16:42:22.436673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '808958024cdf'
down_revision = '6d73fd069cf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('created_time', sa.Integer(), nullable=False))
    op.add_column('comment', sa.Column('updated_time', sa.Integer(), nullable=False))
    op.add_column('store', sa.Column('created_time', sa.Integer(), nullable=False))
    op.add_column('store', sa.Column('updated_time', sa.Integer(), nullable=False))
    op.add_column('user', sa.Column('created_time', sa.Integer(), nullable=False))
    op.add_column('user', sa.Column('updated_time', sa.Integer(), nullable=False))
    op.add_column('user_role', sa.Column('created_time', sa.Integer(), nullable=False))
    op.add_column('user_role', sa.Column('updated_time', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_role', 'updated_time')
    op.drop_column('user_role', 'created_time')
    op.drop_column('user', 'updated_time')
    op.drop_column('user', 'created_time')
    op.drop_column('store', 'updated_time')
    op.drop_column('store', 'created_time')
    op.drop_column('comment', 'updated_time')
    op.drop_column('comment', 'created_time')
    # ### end Alembic commands ###
